---
site_name: IronCore Project
repo_url: https://github.com/ironcore-dev/docs/
edit_uri: edit/main/docs/

theme:
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.indexes
  - navigation.top
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon/favicon.ico
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: "Work Sans"

plugins:
  - search
  - multirepo:
      cleanup: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - codehilite
  - admonition
  - abbr
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Infrastructure as a Service:
      - Getting Started: iaas/getting-started.md
      - Architecture:
        - Overview: iaas/architecture/overview.md
        - Scheduling and Orchestration: iaas/architecture/scheduling.md
        - Operating System Images: iaas/architecture/os-images.md
        - Providers:
            - Overview: iaas/architecture/providers/overview.md
            - RuntimeInterface: iaas/architecture/providers/runtime-interface.md
            - Compute Provider: iaas/architecture/providers/compute.md
            - Storage Provider: iaas/architecture/providers/storage.md
        - Networking: iaas/architecture/networking.md
      - User Guide:
        - Tutorials: iaas/user-guide/index.md
      - Kubernetes Integration:
        - Overview: iaas/kubernetes/overview.md
        - CSI Driver: iaas/kubernetes/csi-driver.md
        - Cloud Controller Manager: iaas/kubernetes/cloud-controller-manager.md
        - Gardener: iaas/kubernetes/gardener.md
      - Operator Guide:
          - Overview: iaas/operations-guide/overview.md
          - Landscape Setup: iaas/operations-guide/landscape-setup.md
      - Components:
          # Add component repo URLs here (Imported repos must have a mkdocs.yml file)
          - Ironcore: "!import https://github.com/ironcore-dev/ironcore?branch=main"
          - Ironcore Net: "!import https://github.com/ironcore-dev/ironcore-net?branch=main"
          - Libvirt Provider: "!import https://github.com/ironcore-dev/libvirt-provider?branch=main"
          - Ceph Provider: "!import https://github.com/ironcore-dev/ceph-provider?branch=main"
  #        - Metalnet: "!import https://github.com/ironcore-dev/metalnet?branch=main"
  #        - DPService: "!import https://github.com/ironcore-dev/dpservice?branch=main"
  #        - Metalbond: "!import https://github.com/ironcore-dev/metalbond?branch=main"
  - Bare Metal Management:
      - Getting Started: baremetal/getting-started.md
      - Architecture:
        - Overview: baremetal/architecture/overview.md
        - Discovery: baremetal/architecture/discovery.md
        - Provisioning: baremetal/architecture/provisioning.md
        - Maintenance: baremetal/architecture/maintenance.md
      - User Guide:
        - Tutorials: baremetal/user-guide/index.md
      - Kubernetes Integration:
        - Overview: baremetal/kubernetes/overview.md
        - Cloud Controller Manager: baremetal/kubernetes/cloud-controller-manager.md
        - Metal Load Balancer Controller: baremetal/kubernetes/load-balancer-controller.md
        - Cluster API: baremetal/kubernetes/cluster-api.md
        - Gardener: baremetal/kubernetes/gardener.md
      - Operator Guide:
          - Overview: baremetal/operations-guide/overview.md
          - Landscape Setup: baremetal/operations-guide/landscape-setup.md
      - Components:
        - Metal Operator: "!import https://github.com/ironcore-dev/metal-operator?branch=main"
        - Boot Operator: "!import https://github.com/ironcore-dev/boot-operator?branch=main"
#        - FeDHCP: "!import https://github.com/ironcore-dev/fedhcp?branch=main"
#        - IPAM: "!import https://github.com/ironcore-dev/ipam?branch=main"
  - Developer Guide: developer-guide/index.md
#  - Upgrade Guide: upgrade-guide/index.md
#  - Troubleshooting: troubleshooting/index.md
  - Contribute:
    - Style Guide: contribute/style-guide.md
    - Contributing: contribute/contributing.md
#  - Support: support/index.md
#  - Roadmap: roadmap/index.md
#  - Releases: releases/index.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ironcore-dev/docs
