---
site_name: IronCore - cloud native Infrastructure as a Service 
plugins:
  - search
  - multirepo:
      repos:
        - section: IronCore
          import_url: 'https://github.com/ironcore-dev/ironcore?branch=main&edit_uri=/blob/main'
        - section: IronCore Net
          import_url: 'https://github.com/ironcore-dev/ironcore-net?branch=main&edit_uri=/blob/main'
        - section: IronCore Metal Operator
          import_url: 'https://github.com/ironcore-dev/metal-operator?branch=main&edit_uri=/blob/main'
theme:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: 'Work Sans'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - codehilite
  - admonition
  - abbr
  - toc:
      permalink: true
